{ name: "Afghanistan", iso_code: "", visited: false },
{ name: "Albania", iso_code: "", visited: false },
{ name: "Algeria", iso_code: "", visited: false },
{ name: "Angola", iso_code: "", visited: false },
{ name: "Antarctica", iso_code: "", visited: false },
{ name: "Argentina", iso_code: "", visited: false },
{ name: "Armenia", iso_code: "", visited: false },
{ name: "Australia", iso_code: "", visited: false },
{ name: "Austria", iso_code: "", visited: false },
{ name: "Azerbaijan", iso_code: "", visited: false },
{ name: "Bahamas", iso_code: "", visited: false },
{ name: "Bangladesh", iso_code: "", visited: false },
{ name: "Belarus", iso_code: "", visited: false },
{ name: "Belgium", iso_code: "", visited: false },
{ name: "Belize", iso_code: "", visited: false },
{ name: "Benin", iso_code: "", visited: false },
{ name: "Bhutan", iso_code: "", visited: false },
{ name: "Bolivia", iso_code: "", visited: false },
{ name: "Bosnia and Herz.", iso_code: "", visited: false },
{ name: "Botswana", iso_code: "", visited: false },
{ name: "Brazil", iso_code: "", visited: false },
{ name: "Brunei", iso_code: "", visited: false },
{ name: "Bulgaria", iso_code: "", visited: false },
{ name: "Burkina Faso", iso_code: "", visited: false },
{ name: "Burundi", iso_code: "", visited: false },
{ name: "Cambodia", iso_code: "", visited: false },
{ name: "Cameroon", iso_code: "", visited: false },
{ name: "Canada", iso_code: "CAN", visited: true },
{ name: "Central African Rep.", iso_code: "", visited: false },
{ name: "Chad", iso_code: "", visited: false },
{ name: "Chile", iso_code: "", visited: false },
{ name: "China", iso_code: "", visited: false },
{ name: "Colombia", iso_code: "", visited: false },
{ name: "Congo", iso_code: "", visited: false },
{ name: "Costa Rica", iso_code: "", visited: false },
{ name: "Croatia", iso_code: "", visited: false },
{ name: "Cuba", iso_code: "", visited: false },
{ name: "Cyprus", iso_code: "", visited: false },
{ name: "Czechia", iso_code: "", visited: false },
{ name: "Côte d'Ivoire", iso_code: "", visited: false },
{ name: "Dem. Rep. Congo", iso_code: "", visited: false },
{ name: "Denmark", iso_code: "", visited: false },
{ name: "Djibouti", iso_code: "", visited: false },
{ name: "Dominican Rep.", iso_code: "", visited: false },
{ name: "Ecuador", iso_code: "", visited: false },
{ name: "Egypt", iso_code: "", visited: false },
{ name: "El Salvador", iso_code: "", visited: false },
{ name: "Eq. Guinea", iso_code: "", visited: false },
{ name: "Eritrea", iso_code: "", visited: false },
{ name: "Estonia", iso_code: "", visited: false },
{ name: "Ethiopia", iso_code: "", visited: false },
{ name: "Falkland Is.", iso_code: "", visited: false },
{ name: "Fiji", iso_code: "", visited: false },
{ name: "Finland", iso_code: "", visited: false },
{ name: "Fr. S. Antarctic Lands", iso_code: "", visited: false },
{ name: "France", iso_code: "FRA", visited: true },
{ name: "Gabon", iso_code: "", visited: false },
{ name: "Gambia", iso_code: "", visited: false },
{ name: "Georgia", iso_code: "", visited: false },
{ name: "Germany", iso_code: "DEU", visited: true },
{ name: "Ghana", iso_code: "", visited: false },
{ name: "Greece", iso_code: "", visited: false },
{ name: "Greenland", iso_code: "", visited: false },
{ name: "Guatemala", iso_code: "", visited: false },
{ name: "Guinea", iso_code: "", visited: false },
{ name: "Guinea-Bissau", iso_code: "", visited: false },
{ name: "Guyana", iso_code: "", visited: false },
{ name: "Haiti", iso_code: "", visited: false },
{ name: "Honduras", iso_code: "", visited: false },
{ name: "Hungary", iso_code: "", visited: false },
{ name: "Iceland", iso_code: "", visited: false },
{ name: "India", iso_code: "", visited: false },
{ name: "Indonesia", iso_code: "", visited: false },
{ name: "Iran", iso_code: "", visited: false },
{ name: "Iraq", iso_code: "", visited: false },
{ name: "Ireland", iso_code: "", visited: false },
{ name: "Israel", iso_code: "", visited: false },
{ name: "Italy", iso_code: "", visited: false },
{ name: "Jamaica", iso_code: "", visited: false },
{ name: "Japan", iso_code: "", visited: false },
{ name: "Jordan", iso_code: "", visited: false },
{ name: "Kazakhstan", iso_code: "", visited: false },
{ name: "Kenya", iso_code: "", visited: false },
{ name: "Kosovo", iso_code: "", visited: false },
{ name: "Kuwait", iso_code: "", visited: false },
{ name: "Kyrgyzstan", iso_code: "", visited: false },
{ name: "Laos", iso_code: "", visited: false },
{ name: "Latvia", iso_code: "", visited: false },
{ name: "Lebanon", iso_code: "", visited: false },
{ name: "Lesotho", iso_code: "", visited: false },
{ name: "Liberia", iso_code: "", visited: false },
{ name: "Libya", iso_code: "", visited: false },
{ name: "Lithuania", iso_code: "", visited: false },
{ name: "Luxembourg", iso_code: "", visited: false },
{ name: "Macedonia", iso_code: "", visited: false },
{ name: "Madagascar", iso_code: "", visited: false },
{ name: "Malawi", iso_code: "", visited: false },
{ name: "Malaysia", iso_code: "", visited: false },
{ name: "Mali", iso_code: "", visited: false },
{ name: "Mauritania", iso_code: "", visited: false },
{ name: "Mexico", iso_code: "", visited: false },
{ name: "Moldova", iso_code: "", visited: false },
{ name: "Mongolia", iso_code: "", visited: false },
{ name: "Montenegro", iso_code: "", visited: false },
{ name: "Morocco", iso_code: "", visited: false },
{ name: "Mozambique", iso_code: "", visited: false },
{ name: "Myanmar", iso_code: "", visited: false },
{ name: "N. Cyprus", iso_code: "", visited: false },
{ name: "Namibia", iso_code: "", visited: false },
{ name: "Nepal", iso_code: "", visited: false },
{ name: "Netherlands", iso_code: "", visited: false },
{ name: "New Caledonia", iso_code: "", visited: false },
{ name: "New Zealand", iso_code: "", visited: false },
{ name: "Nicaragua", iso_code: "", visited: false },
{ name: "Niger", iso_code: "", visited: false },
{ name: "Nigeria", iso_code: "", visited: false },
{ name: "North Korea", iso_code: "", visited: false },
{ name: "Norway", iso_code: "", visited: false },
{ name: "Oman", iso_code: "", visited: false },
{ name: "Pakistan", iso_code: "", visited: false },
{ name: "Palestine", iso_code: "", visited: false },
{ name: "Panama", iso_code: "", visited: false },
{ name: "Papua New Guinea", iso_code: "", visited: false },
{ name: "Paraguay", iso_code: "", visited: false },
{ name: "Peru", iso_code: "", visited: false },
{ name: "Philippines", iso_code: "", visited: false },
{ name: "Poland", iso_code: "", visited: false },
{ name: "Portugal", iso_code: "", visited: false },
{ name: "Puerto Rico", iso_code: "", visited: false },
{ name: "Qatar", iso_code: "", visited: false },
{ name: "Romania", iso_code: "", visited: false },
{ name: "Russia", iso_code: "", visited: false },
{ name: "Rwanda", iso_code: "", visited: false },
{ name: "S. Sudan", iso_code: "", visited: false },
{ name: "Saudi Arabia", iso_code: "", visited: false },
{ name: "Senegal", iso_code: "", visited: false },
{ name: "Serbia", iso_code: "", visited: false },
{ name: "Sierra Leone", iso_code: "", visited: false },
{ name: "Slovakia", iso_code: "", visited: false },
{ name: "Slovenia", iso_code: "", visited: false },
{ name: "Solomon Is.", iso_code: "", visited: false },
{ name: "Somalia", iso_code: "", visited: false },
{ name: "Somaliland", iso_code: "", visited: false },
{ name: "South Africa", iso_code: "", visited: false },
{ name: "South Korea", iso_code: "", visited: false },
{ name: "Spain", iso_code: "", visited: false },
{ name: "Sri Lanka", iso_code: "", visited: false },
{ name: "Sudan", iso_code: "", visited: false },
{ name: "Suriname", iso_code: "", visited: false },
{ name: "Sweden", iso_code: "", visited: false },
{ name: "Switzerland", iso_code: "", visited: false },
{ name: "Syria", iso_code: "", visited: false },
{ name: "Taiwan", iso_code: "", visited: false },
{ name: "Tajikistan", iso_code: "", visited: false },
{ name: "Tanzania", iso_code: "", visited: false },
{ name: "Thailand", iso_code: "", visited: false },
{ name: "Timor-Leste", iso_code: "", visited: false },
{ name: "Togo", iso_code: "", visited: false },
{ name: "Trinidad and Tobago", iso_code: "", visited: false },
{ name: "Tunisia", iso_code: "", visited: false },
{ name: "Turkey", iso_code: "", visited: false },
{ name: "Turkmenistan", iso_code: "", visited: false },
{ name: "Uganda", iso_code: "", visited: false },
{ name: "Ukraine", iso_code: "", visited: false },
{ name: "United Arab Emirates", iso_code: "", visited: false },
{ name: "United Kingdom", iso_code: "GBR", visited: true },
{ name: "United States of America", iso_code: "USA", visited: true },
{ name: "Uruguay", iso_code: "", visited: false },
{ name: "Uzbekistan", iso_code: "", visited: false },
{ name: "Vanuatu", iso_code: "", visited: false },
{ name: "Venezuela", iso_code: "", visited: false },
{ name: "Vietnam", iso_code: "", visited: false },
{ name: "W. Sahara", iso_code: "", visited: false },
{ name: "Yemen", iso_code: "", visited: false },
{ name: "Zambia", iso_code: "", visited: false },
{ name: "Zimbabwe", iso_code: "", visited: false },
{ name: "eSwatini", iso_code: "", visited: false },
